version: "3"
services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:8080 -w 3 main:app --timeout 150
    container_name: caixa_download
    ports:
      - "80:8080"
    volumes:
      - ./lake:/app/lake/
      - ./log:/app/log/
    env_file:
      - .env
    links:
      - database
        
  database:
    image: mongo
    container_name: bd_caixa_download
    ports:
      - "27017:27017"
